export interface MedicalCalculatorItem {
  id: string;
  name: string;
  specialtyId: string;
  specialtyName: string;
  emoji: string;
  category: string;
  description: string;
  formulaOrUtility: string;
  fields?: {
    id: string;
    label: string;
    type: 'number' | 'select' | 'checkbox';
    options?: { label: string; value: number }[];
    unit?: string;
    default?: any;
  }[];
  calculate?: (inputs: Record<string, any>) => { result: string | number; unit?: string; interpretation: string; alertLevel: 'success' | 'warning' | 'danger' | 'info' };
}

export const MEDICAL_SPECIALTIES_CALCULATORS = [
  { id: 'cardiologie', name: 'Cardiologie & Vasculaire', emoji: '🫀', count: 12 },
  { id: 'pneumologie', name: 'Pneumologie & Alvéolaire', emoji: '🫁', count: 8 },
  { id: 'neurologie', name: 'Neurologie & Neurochirurgie', emoji: '🧠', count: 10 },
  { id: 'gastroenterologie', name: 'Gastro-Entérologie & Hépatologie', emoji: '🧪', count: 9 },
  { id: 'nephrologie', name: 'Néphrologie & Électrolytes', emoji: '💧', count: 12 },
  { id: 'urgences', name: 'Urgences, Sepsis & Réanimation', emoji: '🚨', count: 10 },
  { id: 'pediatrie', name: 'Pédiatrie & Néonatologie', emoji: '👶', count: 8 },
  { id: 'chirurgie', name: 'Chirurgie, Anesthésie & Orthopédie', emoji: '🔪', count: 8 },
  { id: 'infectiologie', name: 'Infectiologie & Sepsis', emoji: '🦠', count: 6 },
  { id: 'hematologie', name: 'Hématologie & Oncologie', emoji: '🩸', count: 6 },
  { id: 'gynecologie', name: 'Gynécologie & Obstétrique', emoji: '🤰', count: 6 },
  { id: 'rhumatologie', name: 'Rhumatologie & Os', emoji: '🦴', count: 5 },
  { id: 'psychiatrie', name: 'Psychiatrie & Addictologie', emoji: '🧠', count: 4 },
  { id: 'dermatologie', name: 'Dermatologie & Cutané', emoji: '🧴', count: 3 },
  { id: 'endocrinologie', name: 'Endocrinologie & Métabolisme', emoji: '🦋', count: 3 },
];

export const CALCULATORS_DATABASE: MedicalCalculatorItem[] = [
  // --- CARDIOLOGIE & VASCULAIRE (12) ---
  {
    id: 'chads',
    name: 'Score CHA₂DS₂-VASc',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '🫀',
    category: 'Risque Embolique',
    description: 'Stratification du risque d\'AVC thromboembolique dans la Fibrillation Atriale (FA non valvulaire).',
    formulaOrUtility: 'Recommandations ESC 2020 : Indication d\'anticoagulation si ≥ 1 (H) ou ≥ 2 (F).',
  },
  {
    id: 'hasbled',
    name: 'Score HAS-BLED',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '🩸',
    category: 'Risque Hémorragique',
    description: 'Évaluation du risque de saignement sous traitement anticoagulant (AVK ou AOD).',
    formulaOrUtility: 'Risque élevé si score ≥ 3. Impose la correction des facteurs réversibles.',
  },
  {
    id: 'heart',
    name: 'Score HEART',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '💔',
    category: 'SCA / Douleur Thoracique',
    description: 'Stratification du risque d\'évènement cardiaque majeur (MACE) aux urgences devant une douleur thoracique.',
    formulaOrUtility: 'History, ECG, Age, Risk factors, Troponin (0-10 pts). 0-3: Sortie | 4-6: Observation | 7-10: Coronarographie.',
  },
  {
    id: 'grace',
    name: 'Score GRACE 2.0',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '📈',
    category: 'Infarctus / SCA',
    description: 'Calcul de la mortalité intra-hospitalière et à 6 mois post-Syndrome Coronarien Aigu.',
    formulaOrUtility: 'Guide le délai de coronarographie urgente (<2h si très haut risque, <24h si haut risque).',
  },
  {
    id: 'timi_nstemai',
    name: 'Score TIMI NSTEMI',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '⏱️',
    category: 'Infarctus / SCA',
    description: 'Risque d\'ischémie récurrente ou décès à 14 jours dans le SCA ST-',
    formulaOrUtility: 'Score 0-7 basé sur âge ≥65, ASO, sténose coronarienne, sous-décalage ST, angor sévère, aspirine, troponine.',
  },
  {
    id: 'timi_stemi',
    name: 'Score TIMI STEMI',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '⚡',
    category: 'Infarctus / SCA ST+',
    description: 'Mortalité à 30 jours dans l\'Infarctus du Myocarde avec sus-décalage du segment ST.',
    formulaOrUtility: 'Évalue âge, PAS, FC, classe Killip, sus-décalage ST antérieur, délai de prise en charge.',
  },
  {
    id: 'dapt',
    name: 'Score DAPT (Dual Antiplatelet Therapy)',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '💊',
    category: 'Antiagrégation',
    description: 'Balance bénéfice/risque pour poursuivre la double antiagrégation plaquettaire au-delà de 12 mois après stent.',
    formulaOrUtility: 'Score ≥ 2 favorise la poursuite de la bithérapie. Score < 2 favorise l\'arrêt à 12 mois.',
  },
  {
    id: 'precise_dapt',
    name: 'Score PRECISE-DAPT',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '🩸',
    category: 'Antiagrégation',
    description: 'Prédiction du risque hémorragique hors hôpital sous bithérapie plaquettaire à la sortie de l\'angioplastie.',
    formulaOrUtility: 'Score ≥ 25 indique une bithérapie courte (3 à 6 mois).',
  },
  {
    id: 'ipsr',
    name: 'Index de Pression Systolique (IPSR)',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '🦵',
    category: 'AOMI / Vasculaire',
    description: 'Dépistage de l\'Artériopathie Oblitérante des Membres Inférieurs (PAS cheville / PAS bras).',
    formulaOrUtility: 'Normal 0.90 - 1.30. AOMI si < 0.90 (Sévère si < 0.50). Médiacalcose si > 1.40.',
  },
  {
    id: 'ehra',
    name: 'Score EHRA Fibrillation Atriale',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '🫀',
    category: 'Arythmie / Symptoms',
    description: 'Quantification du retentissement fonctionnel des symptômes de la FA (Stades I à IV).',
    formulaOrUtility: 'I: Aucun symptôme | IIa: Léger | IIb: Modéré | III: Sévère (Activité quotidienne altérée) | IV: Douloureux.',
  },
  {
    id: 'h2fpef',
    name: 'Score H2FPEF',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '🫁',
    category: 'Insuffisance Cardiaque',
    description: 'Probabilité de prévalence d\'une Insuffisance Cardiaque à Fraction d\'Éjection Préservée (ICFEp).',
    formulaOrUtility: 'Heavy, Hypertensive, Atrial Fibrillation, Pulmonary HTN, Elderly, Filling Pressure. Score 0-9.',
  },
  {
    id: 'qtc',
    name: 'QTc Corrigé (Bazett / Fridericia)',
    specialtyId: 'cardiologie',
    specialtyName: 'Cardiologie & Vasculaire',
    emoji: '📉',
    category: 'ECG / Rythmologie',
    description: 'Calcul de l\'intervalle QT corrigé en fonction de la fréquence cardiaque.',
    formulaOrUtility: 'QTc Bazett = QT / √(RR). Normal < 450 ms (H) / < 460 ms (F). Risque Torsades de Pointes si > 500 ms.',
  },

  // --- PNEUMOLOGIE (8) ---
  {
    id: 'wells',
    name: 'Score de Wells EP',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '🫁',
    category: 'Embolie Pulmonaire',
    description: 'Probabilité clinique pré-test devant suspicion d\'Embolie Pulmonaire.',
    formulaOrUtility: 'Score ≤ 1.5 (Faible D-Dimères) | 2-6 (Modéré) | > 6 (Fort Angio-Scanner direct).',
  },
  {
    id: 'geneva',
    name: 'Score de Genève Révisé (EP)',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '📋',
    category: 'Embolie Pulmonaire',
    description: 'Évaluation entièrement explicite et objective du risque d\'Embolie Pulmonaire.',
    formulaOrUtility: 'Âge >65, TVP/EP ant., chirurgie/fracture, cancer, douleur unipodal, hémoptysie, FC, douleur palpation.',
  },
  {
    id: 'perc',
    name: 'Règle PERC (Pulmonary Embolism Rule-out Criteria)',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '🛡️',
    category: 'Embolie Pulmonaire',
    description: 'Élimination d\'une EP sans dosage des D-Dimères chez un patient à risque très faible.',
    formulaOrUtility: '8 critères stricts (Âge < 50, FC < 100, SpO2 ≥ 95%, Pas de TVP/EP, pas d\'œdème, pas d\'hormonothérapie).',
  },
  {
    id: 'curb65',
    name: 'Score CURB-65',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '🫁',
    category: 'Infection Pulmonaire',
    description: 'Orientation d\'hospitalisation (ambulatoire, hospitalisation, réanimation) pour pneumonie aiguë.',
    formulaOrUtility: 'Confusion, Urée > 7 mmol/L, Resp rate ≥ 30, Blood pressure PAS < 90/PAD ≤ 60, Âge ≥ 65 ans (0-5 pts).',
  },
  {
    id: 'crb65',
    name: 'Score CRB-65 (Médecine de Ville)',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '🏠',
    category: 'Infection Pulmonaire',
    description: 'Score CURB-65 simplifié sans dosage d\'urée en biologie ambulatoire.',
    formulaOrUtility: 'Confusion, Respiration ≥ 30, Baisse TA, Âge ≥ 65 ans. 0 pt = Traitement à domicile.',
  },
  {
    id: 'fine_psi',
    name: 'Score Fine (PSI - Pneumonia Severity Index)',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '🏥',
    category: 'Infection Pulmonaire',
    description: 'Stratification fine de la mortalité à 30 jours des Pneumonies Aiguës Communautaires (Classes I à V).',
    formulaOrUtility: 'Prend en compte l\'âge, les comorbidités, l\'examen clinique et les constantes biologiques/radiologiques.',
  },
  {
    id: 'pao2fio2',
    name: 'Ratio PaO₂ / FiO₂ (Score de Kirby)',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '💨',
    category: 'SDRA / Gazométrie',
    description: 'Mesure de l\'altération de l\'hématose et de la sévérité du SDRA (Définition de Berlin).',
    formulaOrUtility: 'Normal > 400 | SDRA Léger 200-300 | Modéré 100-200 | Sévère ≤ 100 mmHg.',
  },
  {
    id: 'act_asthma',
    name: 'Score ACT (Asthma Control Test)',
    specialtyId: 'pneumologie',
    specialtyName: 'Pneumologie & Alvéolaire',
    emoji: '🫁',
    category: 'Asthme / Suivi',
    description: 'Auto-questionnaire à 5 items évaluant le contrôle de l\'asthme sur les 4 dernières semaines.',
    formulaOrUtility: 'Score /25 : < 20 Asthme non contrôlé | 20-24 Bien contrôlé | 25 Contrôle total.',
  },

  // --- NEUROLOGIE & NEUROCHIRURGIE (10) ---
  {
    id: 'glasgow',
    name: 'Score de Coma de Glasgow (GCS)',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '🧠',
    category: 'Coma / Trauma',
    description: 'Évaluation universelle de la profondeur du coma et de l\'état de conscience (3 à 15 pts).',
    formulaOrUtility: 'Ouverture Yeux (1-4) + Réponse Verbale (1-5) + Réponse Motrice (1-6). GCS ≤ 8 = Intubation.',
  },
  {
    id: 'four_score',
    name: 'Score FOUR (Full Outline of UnResponsiveness)',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '👁️',
    category: 'Coma / Réanimation',
    description: 'Alternative moderne au GCS évaluant spécifiquement les réflexes du tronc cérébral et la respiration sous ventilateur.',
    formulaOrUtility: '4 domaines (0-4 pts chaque) : Yeux, Moteur, Tronc cérébral, Respiration. Total / 16.',
  },
  {
    id: 'nihss',
    name: 'Score NIHSS (National Institutes of Health Stroke Scale)',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '⚡',
    category: 'AVC Ischémique',
    description: 'Quantification de la sévérité du déficit neurologique à la phase aiguë de l\'AVC (0 à 42 pts).',
    formulaOrUtility: 'Indication de Thrombolyse / Thrombectomie mécanique et suivi de la revascularisation.',
  },
  {
    id: 'abcd2',
    name: 'Score ABCD²',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '⏱️',
    category: 'AIT / Prévention AVC',
    description: 'Prédiction du risque d\'AVC ischémique à 2, 7 et 90 jours après un Accident Ischémique Transitoire.',
    formulaOrUtility: 'Age ≥60, Blood pressure ≥140/90, Clinical features, Duration of symptoms, Diabetes. (0-7 pts).',
  },
  {
    id: 'hunt_hess',
    name: 'Score de Hunt & Hess',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '🩸',
    category: 'Hémorragie Sous-Arachnoïdienne',
    description: 'Classification clinique de la sévérité d\'une rupture d\'anévrisme cérébral (Grades 1 à 5).',
    formulaOrUtility: 'Grade 1: Asymptomatique / Céphalée légère | Grade 5: Coma profond, décérébration.',
  },
  {
    id: 'fisher',
    name: 'Score de Fisher (TDM Cérébral)',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '📸',
    category: 'Hémorragie Sous-Arachnoïdienne',
    description: 'Prédiction du risque de vasospasme artériel d\'après l\'abondance du sang au scanner sans injection.',
    formulaOrUtility: 'Grade 1 à 4. Grade 3 (hématome épais/caillot > 1mm) a le risque maximal de vasospasme.',
  },
  {
    id: 'wfns',
    name: 'Score WFNS (World Federation of Neurosurgeons)',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '🧠',
    category: 'Hémorragie Sous-Arachnoïdienne',
    description: 'Échelle de sévérité clinique basée sur le GCS et la présence d\'un déficit moteur focal.',
    formulaOrUtility: 'Grades I à V. Pronostic fonctionnel à long terme des hémorragies méningées.',
  },
  {
    id: 'mrs',
    name: 'Échelle de Rankin Modifiée (mRS)',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '♿',
    category: 'Handicap post-AVC',
    description: 'Mesure du degré de dépendance dans la vie quotidienne après un AVC (0 à 6).',
    formulaOrUtility: '0: Aucun symptôme | 2: Handicap léger | 5: Handicap sévère alité | 6: Décès.',
  },
  {
    id: 'edss',
    name: 'Score EDSS (Kurtzke Expanded Disability Status Scale)',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '🚶',
    category: 'Sclérose en Plaques',
    description: 'Évaluation de la progression du handicap neurologique dans la Sclérose en Plaques (0.0 à 10.0).',
    formulaOrUtility: 'Mesure l\'atteinte des 7 systèmes fonctionnels et la distance de marche sans aide.',
  },
  {
    id: 'pediatric_gcs',
    name: 'Score de Glasgow Pédiatrique',
    specialtyId: 'neurologie',
    specialtyName: 'Neurologie & Neurochirurgie',
    emoji: '👶',
    category: 'Pédiatrie / Coma',
    description: 'Adaptation de l\'échelle de Glasgow pour le nourrisson et l\'enfant de moins de 2 ans.',
    formulaOrUtility: 'Évalue les réponses adaptées à l\'âge (babillage, pleurs consolables, retrait).',
  },

  // --- GASTRO-ENTÉROLOGIE & HÉPATOLOGIE (9) ---
  {
    id: 'child_pugh',
    name: 'Score Child-Pugh',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '🧪',
    category: 'Cirrhose / Hépatologie',
    description: 'Évaluation de la réserve fonctionnelle hépatique et du pronostic de la cirrhose (Classes A, B, C).',
    formulaOrUtility: 'Évalue Encéphalopathie, Ascite, Bilirubine, Albumine, Taux de Prothrombine TP / INR.',
  },
  {
    id: 'meld',
    name: 'Score MELD / MELD-Na',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '📊',
    category: 'Cirrhose / Greffe',
    description: 'Priorisation sur la liste d\'attente de transplantation hépatique et mortalité à 3 mois.',
    formulaOrUtility: 'Formule logarithmique basée sur Créatinine, Bilirubine, INR et Natrémie (Score 6 à 40).',
  },
  {
    id: 'ranson',
    name: 'Score de Ranson',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '🔥',
    category: 'Pancréatite Aiguë',
    description: 'Évaluation de la gravité de la pancréatite aiguë calculé à l\'admission H0 et à H48.',
    formulaOrUtility: 'Score ≥ 3 indique une pancréatite aiguë grave avec risque élevé de nécrose et mortalité.',
  },
  {
    id: 'bisap',
    name: 'Score BISAP',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '⚡',
    category: 'Pancréatite Aiguë',
    description: 'Stratification précoce de la mortalité intra-hospitalière dès les 24 premières heures.',
    formulaOrUtility: 'BUN (Urée > 8.9), Impaired mental status (GCS<15), SIRS, Age > 60, Pleural effusion. (0-5 pts).',
  },
  {
    id: 'fib4',
    name: 'Score FIB-4',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '🧬',
    category: 'Fibrose Hépatique',
    description: 'Évaluation non invasive de la fibrose hépatique dans la NASH et les hépatites chroniques.',
    formulaOrUtility: 'Âge x ASAT / (Plaquettes x √ALAT). FIB-4 < 1.30 exclut la fibrose sévère.',
  },
  {
    id: 'apri',
    name: 'Index APRI (AST to Platelet Ratio Index)',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '🩸',
    category: 'Fibrose Hépatique',
    description: 'Dépistage rapide de la cirrhose et fibrose hépatique par rapport ASAT / Plaquettes.',
    formulaOrUtility: '(ASAT / N) / Plaquettes (10^9/L) x 100. Score > 1.00 en faveur d\'une cirrhose.',
  },
  {
    id: 'maddrey',
    name: 'Score de Maddrey (DF - Discriminant Function)',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '🍷',
    category: 'Hépatite Alcoolique',
    description: 'Indication de la corticothérapie dans l\'Hépatite Alcoolique Aiguë Sévère.',
    formulaOrUtility: '4.6 x (TQ patient - TQ témoin) + Bilirubine (mg/dL). Score ≥ 32 = Indication Corticoïdes.',
  },
  {
    id: 'glasgow_blatchford',
    name: 'Score de Glasgow-Blatchford (GBS)',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '🚨',
    category: 'Hémorragie Digestive',
    description: 'Orientation d\'urgence des hémorragies digestives hautes avant toute endoscopie.',
    formulaOrUtility: 'Score = 0 : Prise en charge ambulatoire possible sans hospitalisation en urgence.',
  },
  {
    id: 'rockall',
    name: 'Score de Rockall Complete',
    specialtyId: 'gastroenterologie',
    specialtyName: 'Gastro-Entérologie & Hépatologie',
    emoji: '🩺',
    category: 'Hémorragie Digestive',
    description: 'Prédiction du risque de récidive hémorragique et mortalité après fibroscopie œso-gastro-duodénale.',
    formulaOrUtility: 'Combine l\'âge, l\'état de choc, les comorbidités et les constatations endoscopiques.',
  },

  // --- NÉPHROLOGIE & ÉLECTROLYTES (12) ---
  {
    id: 'cockcroft',
    name: 'DFG Clairance Créatinine (Cockcroft & Gault)',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '💧',
    category: 'Insuffisance Rénale',
    description: 'Estimation de la clairance de la créatinine pour l\'adaptation des posologies médicamenteuses.',
    formulaOrUtility: '((140 - Âge) x Poids / (72 x Créat mg/dL)) x (0.85 si Femme).',
  },
  {
    id: 'ckd_epi',
    name: 'DFG CKD-EPI (2021 sans race)',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🧪',
    category: 'Insuffisance Rénale',
    description: 'Formule internationale recommandée par la HAS et KDIGO pour la classification de la MRC.',
    formulaOrUtility: 'Estimation précise de la filtration glomérulaire indexée sur la surface corporelle (1.73m²).',
  },
  {
    id: 'mdrd',
    name: 'DFG MDRD Simplifié',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '📐',
    category: 'Insuffisance Rénale',
    description: 'Estimation du DFG pour les insuffisances rénales modérées à sévères.',
    formulaOrUtility: '175 x (Créat µmol/188.4)^-1.154 x Âge^-0.203 x (0.742 si Femme).',
  },
  {
    id: 'na_deficit',
    name: 'Déficit en Sodium (Hyponatrémie)',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🧂',
    category: 'Ionogramme',
    description: 'Quantité totale de Na+ (mmol) à administrer pour remonter la natrémie.',
    formulaOrUtility: 'Déficit Na = (Na cible - Na actuel) x Poids x (0.6 H / 0.5 F). Max 8 mmol/L/24h !',
  },
  {
    id: 'water_deficit',
    name: 'Déficit en Eau Libre (Hypernatrémie)',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🚰',
    category: 'Ionogramme',
    description: 'Volume d\'eau pure (Litres) nécessaire pour corriger une déshydratation intracellulaire.',
    formulaOrUtility: 'Déficit Eau = Eau Totale x ((Na actuel / 140) - 1). Réhydratation progressive.',
  },
  {
    id: 'anion_gap',
    name: 'Trou Anionique Plasmatique',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '⚗️',
    category: 'Acidose Métabolique',
    description: 'Orientation diagnostique des acidoses métaboliques à trou anionique élevé ou normal.',
    formulaOrUtility: '[Na+] - ([Cl-] + [HCO3-]). Normal = 12 ± 4 mmol/L. Élevé dans acidose lactique, cétoacidose.',
  },
  {
    id: 'urinary_anion_gap',
    name: 'Trou Anionique Urinaire',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🚽',
    category: 'Acidose Métabolique',
    description: 'Différenciation des acidoses métaboliques hyperchlorémiques (Diarrhée vs Acidose Tubulaire Rénale).',
    formulaOrUtility: '([Na+]u + [K+]u) - [Cl-]u. Négatif = Perte digestive (Diarrhée) | Positif = Cause Rénale.',
  },
  {
    id: 'fena',
    name: 'Excrétion Fractionnelle du Sodium (FENa)',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '💧',
    category: 'Insuffisance Rénale Aiguë',
    description: 'Distinction entre Insuffisance Rénale Aiguë Fonctionnelle (Prérénale) et Organique (Nécrosique).',
    formulaOrUtility: '(Na urinaire / Na sang) / (Créat urinaire / Créat sang) x 100. FENa < 1% = IRA Fonctionnelle.',
  },
  {
    id: 'feurea',
    name: 'Excrétion Fractionnelle de l\'Urée (FEUrea)',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🧪',
    category: 'Insuffisance Rénale Aiguë',
    description: 'Diagnostic d\'IRA fonctionnelle chez les patients traités par Diurétiques de l\'anse.',
    formulaOrUtility: '(Urée urinaire / Urée sang) / (Créat urinaire / Créat sang) x 100. FEUrea < 35% = IRA Fonctionnelle.',
  },
  {
    id: 'corrected_calcium',
    name: 'Calcium Corrigé sur Albumine',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🦴',
    category: 'Ionogramme',
    description: 'Correction de la calcémie totale en cas de dysalbuminémie.',
    formulaOrUtility: 'Ca corrigé (mmol/L) = Ca mesuré + 0.02 x (40 - Albumine g/L).',
  },
  {
    id: 'osmolality',
    name: 'Osmolalité Plasmatique Calculée',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🌊',
    category: 'Osmolarité',
    description: 'Calcul de l\'osmolalité et détection du trou osmolal (Intoxication Méthanol, Éthylène glycol).',
    formulaOrUtility: '2 x [Na+] + Glycémie (mmol/L) + Urée (mmol/L). Normal = 285 - 295 mOsm/kg.',
  },
  {
    id: 'kdigo_ira',
    name: 'Stades KDIGO de l\'IRA',
    specialtyId: 'nephrologie',
    specialtyName: 'Néphrologie & Électrolytes',
    emoji: '🚨',
    category: 'Insuffisance Rénale Aiguë',
    description: 'Classification internationale unifiée de la sévérité de l\'Insuffisance Rénale Aiguë (Stades 1, 2, 3).',
    formulaOrUtility: 'Basée sur la majoration de la créatininémie basale et le débit diurétique horaire (mL/kg/h).',
  },

  // --- URGENCES, SEPSIS & RÉANIMATION (10) ---
  {
    id: 'pse',
    name: 'Calculateur de Débit PSE Vasopresseurs',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '💊',
    category: 'Pharmacologie Garde',
    description: 'Calcul précis du débit en mL/h pour perfusion de Noradrénaline, Dobutamine, Dopamine.',
    formulaOrUtility: 'Formule : (Dose µg/kg/min x Poids kg x 60) / (Concentration mg/mL x 1000).',
  },
  {
    id: 'qsofa',
    name: 'Score qSOFA (Quick SOFA)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '🚨',
    category: 'Sepsis / Urgences',
    description: 'Dépistage ultra-rapide hors réanimation des patients suspects de Sepsis grave.',
    formulaOrUtility: '3 critères (0-3 pts) : FR ≥ 22/min, Altération conscience GCS < 15, PAS ≤ 100 mmHg. Score ≥ 2 = Sepsis.',
  },
  {
    id: 'sofa',
    name: 'Score SOFA (Sequential Organ Failure Assessment)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '🏥',
    category: 'Sepsis / Réanimation',
    description: 'Quantification de la défaillance multiorganique en réanimation (Respiration, Coagulation, Foie, TA, GCS, Rein).',
    formulaOrUtility: 'Augmentation de SOFA ≥ 2 points définit le Sepsis selon Sepsis-3.',
  },
  {
    id: 'apache2',
    name: 'Score APACHE II',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '📊',
    category: 'Mortalité Réanimation',
    description: 'Prédiction de la mortalité intra-hospitalière à l\'admission en réanimation (0 à 71 pts).',
    formulaOrUtility: 'Évalue 12 variables physiologiques aiguës, l\'âge et l\'état de santé antérieur.',
  },
  {
    id: 'saps2',
    name: 'Score IGS II (SAPS II)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '📈',
    category: 'Mortalité Réanimation',
    description: 'Indice de Gravité Simplifié II mesuré à 24 heures de l\'admission en soins intensifs.',
    formulaOrUtility: 'Calcul du risque de mortalité hospitalière utilisé pour les audits de réanimation.',
  },
  {
    id: 'shock_index',
    name: 'Shock Index (Indice de Choc)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '⚡',
    category: 'Choc / Hémodynamique',
    description: 'Détection précoce du choc hypovolémique ou septique avant la chute de la tension artérielle.',
    formulaOrUtility: 'Shock Index = Fréquence Cardiaque / PAS. Normal = 0.5 - 0.7. Choc occulte si > 0.9 !',
  },
  {
    id: 'pam_map',
    name: 'Pression Artérielle Moyenne (PAM)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '🫀',
    category: 'Hémodynamique',
    description: 'Pression de perfusion des organes vitaux (Cerveau, Reins, Cœur).',
    formulaOrUtility: 'PAM = (PAS + 2 x PAD) / 3. Cible thérapeutique minimale en choc septique ≥ 65 mmHg.',
  },
  {
    id: 'wallace_burn',
    name: 'Règle des 9 de Wallace (Brûlures)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '🔥',
    category: 'Traumatologie / Brûlures',
    description: 'Estimation rapide de la Surface Corporelle Brûlée (SCB %) chez l\'adulte.',
    formulaOrUtility: 'Tête 9%, Tarse antérieur 18%, Tarse postérieur 18%, Membre sup 9% x2, Membre inf 18% x2, Périnée 1%.',
  },
  {
    id: 'ganzoni',
    name: 'Déficit en Fer (Formule de Ganzoni)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '💉',
    category: 'Transfusion / Anémie',
    description: 'Calcul de la dose totale de fer injectable (Fer Injectable / Venofer) à administrer.',
    formulaOrUtility: 'Dose Fer (mg) = Poids kg x (Hb cible - Hb actuelle g/dL) x 2.4 + Réseres Fer (500 mg).',
  },
  {
    id: 'rts_trauma',
    name: 'Score RTS (Revised Trauma Score)',
    specialtyId: 'urgences',
    specialtyName: 'Urgences, Sepsis & Réanimation',
    emoji: '🚑',
    category: 'Polytrauma',
    description: 'Triage de terrain des polytraumatisés basé sur le GCS, la PAS et la Fréquence Respiratoire.',
    formulaOrUtility: 'Score 0-12. RTS < 11 indique un transfert direct en Centre de Trauma Majeur (Level 1).',
  },

  // --- PÉDIATRIE & NÉONATOLOGIE (8) ---
  {
    id: 'apgar',
    name: 'Score APGAR',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '👶',
    category: 'Néonatologie',
    description: 'Évaluation de l\'adaptation néonatale à la naissance (1 min, 5 min et 10 min).',
    formulaOrUtility: 'Apparence, Pouls, Grimace, Activité, Respiration (0-10 pts). Normal ≥ 7.',
  },
  {
    id: 'silverman',
    name: 'Score de Silverman',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '🫁',
    category: 'Détresse Respiratoire',
    description: 'Quantification de la détresse respiratoire du nouveau-né et prématuré.',
    formulaOrUtility: '5 signes (0-2 pts) : Balancement thoraco-abdominal, Tirage, Entonnoir xiphoïdien, Battement ailes du nez, Grésillement. 0 = Normal, 10 = Sévère.',
  },
  {
    id: 'pas_asthma_ped',
    name: 'Score PAS (Pediatric Asthma Score)',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '🫁',
    category: 'Asthme Pédiatrique',
    description: 'Évaluation de la sévérité de la crise d\'asthme chez l\'enfant.',
    formulaOrUtility: 'Évalue FR, Sibilants, Tirage, Rapport I/E et SpO2. Guide la fréquence des nébulisations de Salbutamol.',
  },
  {
    id: 'fluid_maintenance_421',
    name: 'Règle des 4-2-1 (Holliday-Segar)',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '🍼',
    category: 'Perfusion Pédiatrique',
    description: 'Calcul du débit de perfusion de maintien en mL/heure chez l\'enfant.',
    formulaOrUtility: '4 mL/kg/h pour les 10 1ers kg + 2 mL/kg/h pour les 10 kg suivants + 1 mL/kg/h au-delà.',
  },
  {
    id: 'westley_croup',
    name: 'Score de Westley (Laryngite / Croup)',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '🗣️',
    category: 'Laryngite Aiguë',
    description: 'Évaluation de l\'obstruction des voies aériennes supérieures dans le Croup.',
    formulaOrUtility: 'Évalue Stridor, Tirage, Entrée d\'air, Cyanose et Conscience. Guide la Dexaméthasone / Adrénaline nébulisée.',
  },
  {
    id: 'pews',
    name: 'Score PEWS (Pediatric Early Warning Score)',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '🚨',
    category: 'Urgence Pédiatrique',
    description: 'Dépistage précoce de la dégradation clinique chez l\'enfant hospitalisé.',
    formulaOrUtility: 'Comportement, Cardiovasculaire, Respiratoire (0-9 pts). PEWS ≥ 4 = Appel réanimateur pédiatrique.',
  },
  {
    id: 'yale_baby',
    name: 'Échelle d\'Observation de Yale (OSY)',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '🌡️',
    category: 'Fièvre du Nourrisson',
    description: 'Évaluation du risque d\'infection bactérienne sévère chez le nourrisson fébrile < 3 mois.',
    formulaOrUtility: 'Qualité des pleurs, Réponse aux parents, Éveil, Coloration, Hydratation, Évaluation sociale (6-30 pts).',
  },
  {
    id: 'pediatric_weight_dose',
    name: 'Estimation Poids & Posologies Pédiatriques',
    specialtyId: 'pediatrie',
    specialtyName: 'Pédiatrie & Néonatologie',
    emoji: '⚖️',
    category: 'Pharmacologie Pédiatrique',
    description: 'Calcul du poids théorique selon l\'âge (Formule d\'Advanced Pediatric Life Support).',
    formulaOrUtility: 'Poids (1-10 ans) = (Âge + 4) x 2 kg. Calcule les doses de Paracétamol (15 mg/kg) et Ibuprofène.',
  },

  // --- CHIRURGIE, ANESTHÉSIE & ORTHOPÉDIE (8) ---
  {
    id: 'alvarado',
    name: 'Score d\'Alvarado (MANTRELS)',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '🔪',
    category: 'Appendicite Aiguë',
    description: 'Diagnostic clinique et biologique de l\'Appendicite Aiguë chez l\'adulte.',
    formulaOrUtility: 'Migration douleur, Anorexie, Nausées, Tendresse FID, Rebond, Élévation temp, Leucocytose, Shift PNN. (0-10 pts).',
  },
  {
    id: 'pas_appendicitis',
    name: 'Score PAS Pédiatrique (Pediatric Appendicitis Score)',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '👶',
    category: 'Appendicite Pédiatrique',
    description: 'Score validé spécifique pour l\'appendicite chez l\'enfant et l\'adolescent.',
    formulaOrUtility: 'Score ≤ 3 exclut l\'appendicite. Score ≥ 6 nécessite échographie / chirurgie.',
  },
  {
    id: 'asa_class',
    name: 'Classification ASA (American Society of Anesthesiologists)',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '🩺',
    category: 'Anesthésie / Risque Opératoire',
    description: 'Évaluation de l\'état de santé pré-opératoire du patient (Classes I à VI).',
    formulaOrUtility: 'ASA 1: Patient sain | ASA 2: Pathologie modérée | ASA 3: Pathologie sévère | ASA 4: Menace vitale constante.',
  },
  {
    id: 'ottawa_ankle',
    name: 'Règles de la Cheville d\'Ottawa (Ottawa Ankle Rules)',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '🦶',
    category: 'Traumatologie Orthopédique',
    description: 'Indication des radiographies de la cheville et du pied après traumatisme aigu.',
    formulaOrUtility: 'Sensibilité 100%. Évite 95% de radios inutiles si marche 4 pas possible et absence de douleur osseuse ciblée.',
  },
  {
    id: 'ottawa_knee',
    name: 'Règles du Genou d\'Ottawa',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '🦵',
    category: 'Traumatologie Orthopédique',
    description: 'Indication de la radiographie du genou post-traumatique.',
    formulaOrUtility: 'Radio si âge ≥ 55, douleur rotule/tête péroné, flexion < 90°, ou incapacité de faire 4 pas.',
  },
  {
    id: 'caprini',
    name: 'Score de Caprini VTE',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '💉',
    category: 'Thromboprophylaxie',
    description: 'Stratification du risque thrombo-embolique chez le patient chirurgical.',
    formulaOrUtility: 'Guide la durée et le type de thromboprophylaxie par HBPM et bas de contention post-opératoire.',
  },
  {
    id: 'padua',
    name: 'Score de PADUA',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '📋',
    category: 'Thromboprophylaxie',
    description: 'Risque de maladie thrombo-embolique veineuse chez le patient hospitalisé en médecine.',
    formulaOrUtility: 'Score ≥ 4 = Risque élevé : Indication d\'une prévention par HBPM (Lovenox 4000 UI/j).',
  },
  {
    id: 'possum',
    name: 'Score POSSUM / p-POSSUM',
    specialtyId: 'chirurgie',
    specialtyName: 'Chirurgie, Anesthésie & Orthopédie',
    emoji: '📈',
    category: 'Chirurgie Générale',
    description: 'Prédiction de la morbidité et mortalité chirurgicale ajustée au risque.',
    formulaOrUtility: 'Combine 12 variables physiologiques et 6 variables opératoires.',
  },

  // --- INFECTIOLOGIE & SEPSIS (6) ---
  {
    id: 'centor',
    name: 'Score de Centor / McIsaac',
    specialtyId: 'infectiologie',
    specialtyName: 'Infectiologie & Sepsis',
    emoji: '🦠',
    category: 'Angine Aiguë',
    description: 'Indication du Test de Diagnostic Rapide (TDR) Streptocoque A dans les angines.',
    formulaOrUtility: 'Fièvre >38°C, Exsudat amygdalien, Adénopathies cervicales sensibles, Absence de toux, Âge (0-5 pts). Score ≥ 2 = TDR.',
  },
  {
    id: 'sirs',
    name: 'Critères de SIRS (Syndrome Inflammatoire)',
    specialtyId: 'infectiologie',
    specialtyName: 'Infectiologie & Sepsis',
    emoji: '🔥',
    category: 'Infection / Inflammation',
    description: 'Définition historique de la réponse inflammatoire systémique.',
    formulaOrUtility: 'SIRS présent si ≥ 2 critères : Temp > 38°C ou < 36°C, FC > 90, FR > 20, Leucocytes > 12k ou < 4k.',
  },
  {
    id: 'mascc',
    name: 'Score MASCC (Neutropénie Fébrile)',
    specialtyId: 'infectiologie',
    specialtyName: 'Infectiologie & Sepsis',
    emoji: '🛡️',
    category: 'Onco-Infectiologie',
    description: 'Identification des neutropénies fébriles à faible risque pouvant être traitées par antibiothérapie orale.',
    formulaOrUtility: 'Score MASCC ≥ 21 = Faible risque (Ambulatoire possible sous Augmentin + Ciprofloxacine).',
  },
  {
    id: 'pist',
    name: 'Score PIST Pneumonie',
    specialtyId: 'infectiologie',
    specialtyName: 'Infectiologie & Sepsis',
    emoji: '🫁',
    category: 'Pneumologie Infectieuse',
    description: 'Évaluation du risque bactérien dans les infections bronchiques.',
    formulaOrUtility: 'Guide l\'antibiothérapie raisonnée et évite la surprescription.',
  },
  {
    id: 'sofa_infectio',
    name: 'Score SOFA Sepsis',
    specialtyId: 'infectiologie',
    specialtyName: 'Infectiologie & Sepsis',
    emoji: '🚨',
    category: 'Sepsis',
    description: 'Définition officielle Sepsis-3 : Infection + Variation SOFA ≥ 2 points.',
    formulaOrUtility: 'Choc septique si besoin de vasopresseurs pour PAM ≥ 65 et Lactates > 2 mmol/L malgré remplissage.',
  },
  {
    id: 'fine_infectio',
    name: 'Classifiacation FINE Pneumonie',
    specialtyId: 'infectiologie',
    specialtyName: 'Infectiologie & Sepsis',
    emoji: '🏥',
    category: 'Pneumonie',
    description: 'Classes I à V pour le choix de l\'antibiothérapie et du lieu de prise en charge.',
    formulaOrUtility: 'Classe I-II : Ambulatoire (Amoxicilline) | Classe IV-V : Hospitalisation (C3G + Macrolide).',
  },

  // --- HÉMATOLOGIE & ONCOLOGIE (6) ---
  {
    id: 'khorana',
    name: 'Score de Khorana',
    specialtyId: 'hematologie',
    specialtyName: 'Hématologie & Oncologie',
    emoji: '🩸',
    category: 'Thrombose & Cancer',
    description: 'Prédiction du risque de maladie thromboembolique chez le patient sous chimiothérapie ambulatoire.',
    formulaOrUtility: 'Score ≥ 2 = Haut risque : Indication d\'une thromboprophylaxie par AOD (Rivaroxaban / Apixaban).',
  },
  {
    id: 'ipi_lymphoma',
    name: 'Score IPI (International Prognostic Index)',
    specialtyId: 'hematologie',
    specialtyName: 'Hématologie & Oncologie',
    emoji: '🔬',
    category: 'Lymphome Diffus à Grandes Cellules B',
    description: 'Stratification pronostique du LDGCB.',
    formulaOrUtility: 'Âge > 60, Stade Ann Arbor III/IV, LDH > N, Performance Status ≥ 2, > 1 site ganglionnaire.',
  },
  {
    id: 'flipi',
    name: 'Score FLIPI (Lymphome Folliculaire)',
    specialtyId: 'hematologie',
    specialtyName: 'Hématologie & Oncologie',
    emoji: '🧬',
    category: 'Lymphome Indolent',
    description: 'Index pronostique international spécifique du Lymphome Folliculaire.',
    formulaOrUtility: 'Âge > 60, Stade III/IV, Hémoglobine < 12 g/dL, LDH > N, > 4 zones ganglionnaires.',
  },
  {
    id: 'ipss_r',
    name: 'Score IPSS-R (Syndromes Myélodysplasiques)',
    specialtyId: 'hematologie',
    specialtyName: 'Hématologie & Oncologie',
    emoji: '🩸',
    category: 'Myélodysplasie',
    description: 'Évaluation révisée du risque de transformation en Leucémie Aiguë Myéloïde (LAM).',
    formulaOrUtility: 'Prend en compte la cytogénétique, les blastes médullaires, l\'Hb, les plaquettes et les PNN.',
  },
  {
    id: 'iss_myeloma',
    name: 'Score ISS Myélome Multiple',
    specialtyId: 'hematologie',
    specialtyName: 'Hématologie & Oncologie',
    emoji: '🦴',
    category: 'Myélome Multiple',
    description: 'Stadification du myélome multiple (Stades I, II, III).',
    formulaOrUtility: 'Basé uniquement sur la Bêta-2 microglobuline et l\'Albumine sérique.',
  },
  {
    id: 'isth_dic',
    name: 'Score ISTH de CIVD',
    specialtyId: 'hematologie',
    specialtyName: 'Hématologie & Oncologie',
    emoji: '🩸',
    category: 'Coagulation',
    description: 'Diagnostic biologique formel de la Coagulation Intravasculaire Disseminée.',
    formulaOrUtility: 'Plaquettes, D-Dimères / Monomères de Fibrine, Allongement du TP, Fibrinogène. Score ≥ 5 = CIVD manifeste.',
  },

  // --- GYNÉCOLOGIE & OBSTÉTRIQUE (6) ---
  {
    id: 'bishop',
    name: 'Score de Bishop',
    specialtyId: 'gynecologie',
    specialtyName: 'Gynécologie & Obstétrique',
    emoji: '🤰',
    category: 'Maturation Cervicale',
    description: 'Évaluation de la favorabilité du col utérin avant induction / déclenchement du travail.',
    formulaOrUtility: 'Dilation, Effacement, Consistance, Position du col, Hauteur de la présentation (0-13 pts). Score ≥ 6 = Col favorable.',
  },
  {
    id: 'manning',
    name: 'Score de Manning (Profil Biophysique Fœtal)',
    specialtyId: 'gynecologie',
    specialtyName: 'Gynécologie & Obstétrique',
    emoji: '👶',
    category: 'Bien-être Fœtal',
    description: 'Évaluation échographique et cardiotocographique du bien-être fœtal in utero.',
    formulaOrUtility: 'Mouvements respiratoires, Mouvements fœtaux, Tonus fœtal, Liquide amniotique, RCF. Score 8-10 = Normal.',
  },
  {
    id: 'naegele',
    name: 'Calcul de Terme (Règle de Naegele)',
    specialtyId: 'gynecologie',
    specialtyName: 'Gynécologie & Obstétrique',
    emoji: '📅',
    category: 'Datation Grossesse',
    description: 'Estimation de la date présumée d\'accouchement (DPA) à partir du 1er jour des dernières règles (DDR).',
    formulaOrUtility: 'DPA = DDR + 7 jours + 9 mois (ou - 3 mois). Datation exacte ajustée sur la LCC échographique T1.',
  },
  {
    id: 'pop_q',
    name: 'Score POP-Q (Pelvic Organ Prolapse)',
    specialtyId: 'gynecologie',
    specialtyName: 'Gynécologie & Obstétrique',
    emoji: '🩺',
    category: 'Urogynécologie',
    description: 'Stadification anatomique standardisée des prolapsus génitaux de la femme (Stades 0 à IV).',
    formulaOrUtility: 'Mesure anatomique en cm par rapport à l\'hymen des points Aa, Ba, C, D, Ap, Bp.',
  },
  {
    id: 'rmi_ovary',
    name: 'Index RMI (Risk of Malignancy Index)',
    specialtyId: 'gynecologie',
    specialtyName: 'Gynécologie & Obstétrique',
    emoji: '🔬',
    category: 'Onco-Gynécologie',
    description: 'Estimation du risque de malignité devant une masse ou un kyste ovarien.',
    formulaOrUtility: 'RMI = Score Échographique x Statut Ménopausique x CA-125 (UI/mL). RMI > 200 = Évoque un cancer.',
  },
  {
    id: 'preeclampsia_risk',
    name: 'Score de Risque de Pré-éclampsie',
    specialtyId: 'gynecologie',
    specialtyName: 'Gynécologie & Obstétrique',
    emoji: '⚠️',
    category: 'Hypertension & Grossesse',
    description: 'Dépistage précoce au T1 du risque de pré-éclampsie sévère.',
    formulaOrUtility: 'Indication de l\'Aspirine 160 mg/j débutée avant 16 SA si facteur de risque majeur.',
  },

  // --- RHUMATOLOGIE & OS (5) ---
  {
    id: 'das28',
    name: 'Score DAS28 (Disease Activity Score)',
    specialtyId: 'rhumatologie',
    specialtyName: 'Rhumatologie & Os',
    emoji: '🦴',
    category: 'Polyarthrite Rhumatoïde',
    description: 'Évaluation de l\'activité de la Polyarthrite Rhumatoïde sur 28 articulations.',
    formulaOrUtility: 'Compte articulations douloureuses/gonflées, VS/CRP et Échelle visuelle analogique. DAS28 < 2.6 = Rémission.',
  },
  {
    id: 'frax',
    name: 'Score FRAX (Risque de Fracture)',
    specialtyId: 'rhumatologie',
    specialtyName: 'Rhumatologie & Os',
    emoji: '🦴',
    category: 'Ostéopénie / Ostéoporose',
    description: 'Calcul du risque à 10 ans de fracture ostéoporotique majeure et fracture de hanche (OMS).',
    formulaOrUtility: 'Indique si un traitement anti-ostéoporotique (Bisfosphonates) est nécessaire en plus de la DMO.',
  },
  {
    id: 'basdai',
    name: 'Score BASDAI (Spondylarthrite Ankylosante)',
    specialtyId: 'rhumatologie',
    specialtyName: 'Rhumatologie & Os',
    emoji: '🦴',
    category: 'Spondyloarthrite',
    description: 'Évaluation de l\'activité inflammatoire axiale ressentie par le patient.',
    formulaOrUtility: 'Questionnaire /10. BASDAI ≥ 4 traduit une maladie active nécessitant l\'introduction d\'Anti-TNF Alpha.',
  },
  {
    id: 'sledai',
    name: 'Score SLEDAI (Lupus Érythémateux Systémique)',
    specialtyId: 'rhumatologie',
    specialtyName: 'Rhumatologie & Os',
    emoji: '🦋',
    category: 'Connectivite / Lupus',
    description: 'Indice d\'activité globale du Lupus sur les 10 derniers jours.',
    formulaOrUtility: 'Prend en compte l\'atteinte rénale (protéinurie), neurologique, articulations, éruption et complément C3/C4.',
  },
  {
    id: 'gout_criteria',
    name: 'Critères ACR/EULAR Goutte',
    specialtyId: 'rhumatologie',
    specialtyName: 'Rhumatologie & Os',
    emoji: '👣',
    category: 'Microcristallin',
    description: 'Classification diagnostique de l\'accès goutteux aigu.',
    formulaOrUtility: 'Atteinte MTP1, Tophus, Hyperuricémie > 420 µmol/L, Épanchement cristallin (Microscopie).',
  },

  // --- PSYCHIATRIE & ADDICTOLOGIE (4) ---
  {
    id: 'sad_persons',
    name: 'Score SAD PERSONS',
    specialtyId: 'psychiatrie',
    specialtyName: 'Psychiatrie & Addictologie',
    emoji: '🧠',
    category: 'Risque Suicidaire',
    description: 'Évaluation du risque de récidive ou de passage à l\'acte suicidaire aux urgences.',
    formulaOrUtility: 'Sex, Age, Depression, Previous attempt, Ethanol, Rational thinking loss, Social support, Organized plan, No spouse, Sickness.',
  },
  {
    id: 'cage_deta',
    name: 'Questionnaire CAGE / DETA',
    specialtyId: 'psychiatrie',
    specialtyName: 'Psychiatrie & Addictologie',
    emoji: '🍷',
    category: 'Addictologie Alcool',
    description: 'Dépistage rapide d\'une consommation d\'alcool problématique ou dépendance.',
    formulaOrUtility: 'Diminuer, Entourage, Trop, Alcool le matin. Score ≥ 2 = Très forte présomption de dépendance.',
  },
  {
    id: 'phq9',
    name: 'Questionnaire PHQ-9 (Dépression)',
    specialtyId: 'psychiatrie',
    specialtyName: 'Psychiatrie & Addictologie',
    emoji: '😔',
    category: 'Troubles de l\'Humeur',
    description: 'Auto-questionnaire à 9 items évaluant la sévérité d\'un épisode dépressif majeur (DSM-5).',
    formulaOrUtility: '0-4: Léger | 5-9: Modéré | 10-14: Modérément sévère | 15-27: Épisode dépressif sévère.',
  },
  {
    id: 'gad7',
    name: 'Questionnaire GAD-7 (Anxiété)',
    specialtyId: 'psychiatrie',
    specialtyName: 'Psychiatrie & Addictologie',
    emoji: '⚡',
    category: 'Troubles Anxieux',
    description: 'Évaluation de l\'intensité du Trouble Anxiété Généralisée.',
    formulaOrUtility: 'Score /21. 5: Anxiété légère | 10: Anxiété modérée | 15: Anxiété sévère.',
  },

  // --- DERMATOLOGIE & CUTANÉ (3) ---
  {
    id: 'scorad',
    name: 'Score SCORAD (Dermatite Atopique)',
    specialtyId: 'dermatologie',
    specialtyName: 'Dermatologie & Cutané',
    emoji: '🧴',
    category: 'Eczéma / Atopie',
    description: 'Indice de sévérité globale de la dermatite atopique (Étendue, Intégrité, Symptômes).',
    formulaOrUtility: 'Guide l\'indication des biothérapies (Dupilumab) si SCORAD > 50 (Forme sévère).',
  },
  {
    id: 'pasi',
    name: 'Score PASI (Psoriasis Area and Severity Index)',
    specialtyId: 'dermatologie',
    specialtyName: 'Dermatologie & Cutané',
    emoji: '🔴',
    category: 'Psoriasis',
    description: 'Mesure de référence de l\'étendue et de la sévérité du Psoriasis en plaques (0 à 72).',
    formulaOrUtility: 'Évalue Érythème, Induration, Desquamation sur Tête, Tronc, Bras et Jambes. PASI > 10 = Modéré à sévère.',
  },
  {
    id: 'abcde_melanoma',
    name: 'Règle ABCDE du Mélanome',
    specialtyId: 'dermatologie',
    specialtyName: 'Dermatologie & Cutané',
    emoji: '🔍',
    category: 'Onco-Dermatologie',
    description: 'Dépistage clinique visuel des lésions mélanocytaires suspectes de mélanome.',
    formulaOrUtility: 'Asymétrie, Bords irréguliers, Couleur inhomogène, Diamètre > 6 mm, Évolution récente.',
  },

  // --- ENDOCRINOLOGIE & MÉTABOLISME (3) ---
  {
    id: 'homa_ir',
    name: 'Index HOMA-IR (Insulino-Résistance)',
    specialtyId: 'endocrinologie',
    specialtyName: 'Endocrinologie & Métabolisme',
    emoji: '🦋',
    category: 'Diabétologie',
    description: 'Évaluation biologique de l\'insulino-résistance dans le syndrome métabolique et le SOPK.',
    formulaOrUtility: '(Insulinémie à jeun µUI/mL x Glycémie à jeun mmol/L) / 22.5. HOMA-IR > 2.4 = Insulino-résistance.',
  },
  {
    id: 'calcium_correction_endo',
    name: 'Calcémie Corrigée',
    specialtyId: 'endocrinologie',
    specialtyName: 'Endocrinologie & Métabolisme',
    emoji: '🦴',
    category: 'Parathyroïde',
    description: 'Ajustement de la calcémie totale en cas d\'hypoalbumine.',
    formulaOrUtility: 'Ca corr (mmol/L) = Ca mesuré + 0.02 x (40 - Albumine g/L). Dépistage hyperparathyroïdie.',
  },
  {
    id: 'ferriman_gallwey',
    name: 'Score de Ferriman-Gallwey Modifié',
    specialtyId: 'endocrinologie',
    specialtyName: 'Endocrinologie & Métabolisme',
    emoji: '💇‍♀️',
    category: 'Hirsutisme / SOPK',
    description: 'Quantification de l\'hirsutisme et de l\'hyperandrogénie chez la femme sur 9 zones corporelles.',
    formulaOrUtility: 'Score 0-36. Score ≥ 8 confirme un hirsutisme clinique (Recherche SOPK / Bloc surrénalien).',
  }
];
