import { Specialty, Course, Fiche, QCM, CATProtocol, ClinicalCase, ECGRecord, Medication, User, PlatformSettings } from '@/types';

export const ALL_SPECIALTIES: Specialty[] = [
  {
    "id": "anat_1",
    "slug": "anatomie-1",
    "name": "Anatomie I (Généralités & Membres)",
    "shortName": "Anatomie I",
    "iconName": "Bone",
    "color": "#3B82F6",
    "description": "Ostéologie, arthrologie, myologie et vascularisation des membres supérieur et inférieur.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 14,
    "totalQcms": 90,
    "totalCat": 2,
    "totalFiches": 10
  },
  {
    "id": "cyto_embryo",
    "slug": "cytologie-embryologie",
    "name": "Cytologie & Embryologie",
    "shortName": "Cyto-Embryo",
    "iconName": "Sparkles",
    "color": "#8B5CF6",
    "description": "Structure cellulaire, organites, gamétogenèse, fécondation et 4 premières semaines de développement.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 80,
    "totalCat": 2,
    "totalFiches": 8
  },
  {
    "id": "histo_1",
    "slug": "histologie-generale",
    "name": "Histologie Générale",
    "shortName": "Histologie I",
    "iconName": "Layers",
    "color": "#06B6D4",
    "description": "Tissus fondamentaux : épithéliums, conjonctifs, musculaires, nerveux et sanguins.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 10,
    "totalQcms": 70,
    "totalCat": 2,
    "totalFiches": 8
  },
  {
    "id": "biochim_1",
    "slug": "biochimie-structurale",
    "name": "Biochimie Structurale",
    "shortName": "Biochimie I",
    "iconName": "Atom",
    "color": "#10B981",
    "description": "Structure et propriétés des glucides, lipides, acides aminés, protéines et acides nucléiques.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 85,
    "totalCat": 2,
    "totalFiches": 9
  },
  {
    "id": "biophysique",
    "slug": "biophysique",
    "name": "Biophysique Médicale",
    "shortName": "Biophysique",
    "iconName": "Activity",
    "color": "#F59E0B",
    "description": "Optique médicale, rayonnements ionisants, imagerie, hémodynamique et solutions.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 11,
    "totalQcms": 75,
    "totalCat": 2,
    "totalFiches": 8
  },
  {
    "id": "physio_1",
    "slug": "physiologie-generale",
    "name": "Physiologie Générale",
    "shortName": "Physiologie I",
    "iconName": "HeartPulse",
    "color": "#EF4444",
    "description": "Milieu intérieur, transport membranaire, électrophysiologie cellulaire et potentiels d action.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 10,
    "totalQcms": 70,
    "totalCat": 2,
    "totalFiches": 8
  },
  {
    "id": "chimie",
    "slug": "chimie-medicale",
    "name": "Chimie Médicale & Organique",
    "shortName": "Chimie",
    "iconName": "FlaskConical",
    "color": "#14B8A6",
    "description": "Chimie générale en solution, équilibres acido-basiques, oxydoréduction et fonctions organiques.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 9,
    "totalQcms": 65,
    "totalCat": 1,
    "totalFiches": 6
  },
  {
    "id": "sante_pub_1",
    "slug": "sante-publique-1",
    "name": "Santé Publique & Biostatistiques",
    "shortName": "Santé Publique I",
    "iconName": "BookOpen",
    "color": "#6366F1",
    "description": "Démographie médicale, statistiques descriptives, probabilités et système de santé algérien.",
    "year": 1,
    "faculty": "TOUS",
    "totalCourses": 8,
    "totalQcms": 60,
    "totalCat": 1,
    "totalFiches": 6
  },
  {
    "id": "anat_2",
    "slug": "anatomie-2",
    "name": "Anatomie II (Tronc & Tête-Cou)",
    "shortName": "Anatomie II",
    "iconName": "Bone",
    "color": "#2563EB",
    "description": "Anatomie du thorax, abdomen, pelvis, périnée, tête et cou, et système nerveux central.",
    "year": 2,
    "faculty": "TOUS",
    "totalCourses": 16,
    "totalQcms": 110,
    "totalCat": 3,
    "totalFiches": 12
  },
  {
    "id": "physio_2",
    "slug": "physiologie-grandes-fonctions",
    "name": "Physiologie des Grandes Fonctions",
    "shortName": "Physiologie II",
    "iconName": "HeartPulse",
    "color": "#DC2626",
    "description": "Physiologie cardiovasculaire, respiratoire, rénale, digestive, endocrinienne et neuro-sensorielle.",
    "year": 2,
    "faculty": "TOUS",
    "totalCourses": 18,
    "totalQcms": 125,
    "totalCat": 4,
    "totalFiches": 14
  },
  {
    "id": "biochim_2",
    "slug": "biochimie-metabolique",
    "name": "Biochimie Métabolique",
    "shortName": "Biochimie II",
    "iconName": "Atom",
    "color": "#059669",
    "description": "Métabolisme glucidique, lipidique, azoté, bioénergétique et intégration métabolique.",
    "year": 2,
    "faculty": "TOUS",
    "totalCourses": 14,
    "totalQcms": 95,
    "totalCat": 2,
    "totalFiches": 10
  },
  {
    "id": "histo_2",
    "slug": "histologie-speciale",
    "name": "Histologie Spéciale (Organes)",
    "shortName": "Histologie II",
    "iconName": "Layers",
    "color": "#0891B2",
    "description": "Organisation microscopique des appareils circulatoire, respiratoire, digestif, urinaire et génital.",
    "year": 2,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 80,
    "totalCat": 2,
    "totalFiches": 9
  },
  {
    "id": "semiologie",
    "slug": "semiologie-medicale-chirurgicale",
    "name": "Sémiologie Médicale & Chirurgicale",
    "shortName": "Sémiologie",
    "iconName": "Stethoscope",
    "color": "#7C3AED",
    "description": "Examen clinique méthodique, signes physiques et fonctionnels des différents appareils.",
    "year": 2,
    "faculty": "TOUS",
    "totalCourses": 20,
    "totalQcms": 140,
    "totalCat": 6,
    "totalFiches": 15
  },
  {
    "id": "immuno_1",
    "slug": "immunologie-fondamentale",
    "name": "Immunologie Fondamentale",
    "shortName": "Immunologie I",
    "iconName": "ShieldAlert",
    "color": "#EA580C",
    "description": "Immunité innée et adaptative, antigènes, anticorps, complexe majeur d histocompatibilité.",
    "year": 2,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 85,
    "totalCat": 2,
    "totalFiches": 9
  },
  {
    "id": "genetique",
    "slug": "genetique-medicale",
    "name": "Génétique Médicale",
    "shortName": "Génétique",
    "iconName": "Dna",
    "color": "#D97706",
    "description": "Hérédité mendélienne, cytogénétique, anomalies chromosomiques et conseil génétique.",
    "year": 2,
    "faculty": "TOUS",
    "totalCourses": 9,
    "totalQcms": 60,
    "totalCat": 2,
    "totalFiches": 7
  },
  {
    "id": "pharmaco",
    "slug": "pharmacologie-generale",
    "name": "Pharmacologie Générale & Spéciale",
    "shortName": "Pharmacologie",
    "iconName": "Pill",
    "color": "#BE123C",
    "description": "Pharmacocinétique, pharmacodynamie, classes thérapeutiques, interactions et effets indésirables.",
    "year": 3,
    "faculty": "TOUS",
    "totalCourses": 16,
    "totalQcms": 115,
    "totalCat": 5,
    "totalFiches": 12
  },
  {
    "id": "anapath",
    "slug": "anatomie-pathologique",
    "name": "Anatomie Pathologique Générale",
    "shortName": "Anapath",
    "iconName": "Microscope",
    "color": "#9333EA",
    "description": "Lésions cellulaires et tissulaires, inflammation, processus tumoraux bénins et malins.",
    "year": 3,
    "faculty": "TOUS",
    "totalCourses": 14,
    "totalQcms": 100,
    "totalCat": 4,
    "totalFiches": 10
  },
  {
    "id": "microbio",
    "slug": "microbiologie-bacterio-viro",
    "name": "Microbiologie (Bactériologie & Virologie)",
    "shortName": "Microbiologie",
    "iconName": "Bug",
    "color": "#0D9488",
    "description": "Bactéries pathogènes, virus à ADN et ARN, diagnostic virologique et antibiogramme.",
    "year": 3,
    "faculty": "TOUS",
    "totalCourses": 16,
    "totalQcms": 110,
    "totalCat": 5,
    "totalFiches": 12
  },
  {
    "id": "parasito",
    "slug": "parasitologie-mycologie",
    "name": "Parasitologie & Mycologie",
    "shortName": "Parasitologie",
    "iconName": "Bug",
    "color": "#65A30D",
    "description": "Protozoaires, helminthes, champignons opportunistes, diagnostic et cycles parasitaires.",
    "year": 3,
    "faculty": "TOUS",
    "totalCourses": 13,
    "totalQcms": 90,
    "totalCat": 4,
    "totalFiches": 10
  },
  {
    "id": "immuno_clin",
    "slug": "immunologie-clinique",
    "name": "Immunologie Clinique",
    "shortName": "Immuno Clinique",
    "iconName": "ShieldAlert",
    "color": "#C026D3",
    "description": "Hypersensibilités, maladies auto-immunes, déficits immunitaires et immunopathologie.",
    "year": 3,
    "faculty": "TOUS",
    "totalCourses": 11,
    "totalQcms": 80,
    "totalCat": 4,
    "totalFiches": 8
  },
  {
    "id": "physiopath",
    "slug": "physiopathologie",
    "name": "Physiopathologie Générale",
    "shortName": "Physiopathologie",
    "iconName": "ActivitySquare",
    "color": "#E11D48",
    "description": "Mécanismes des désordres acido-basiques, hydro-électrolytiques, ischémie et choc.",
    "year": 3,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 85,
    "totalCat": 4,
    "totalFiches": 9
  },
  {
    "id": "cardio",
    "slug": "cardiologie",
    "name": "Cardiologie & Pathologies Vasculaires",
    "shortName": "Cardiologie",
    "iconName": "HeartPulse",
    "color": "#EF4444",
    "description": "Coronaropathies, valvulopathies, insuffisance cardiaque, troubles du rythme, HTA et ECG.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 18,
    "totalQcms": 120,
    "totalCat": 8,
    "totalFiches": 14
  },
  {
    "id": "pneumo",
    "slug": "pneumologie",
    "name": "Pneumologie",
    "shortName": "Pneumologie",
    "iconName": "Wind",
    "color": "#06B6D4",
    "description": "Tuberculose pulmonaire, asthme, BPCO, pneumopathies, embolie pulmonaire et EFR.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 15,
    "totalQcms": 95,
    "totalCat": 6,
    "totalFiches": 12
  },
  {
    "id": "neuro",
    "slug": "neurologie",
    "name": "Neurologie",
    "shortName": "Neurologie",
    "iconName": "Brain",
    "color": "#8B5CF6",
    "description": "Accidents vasculaires cérébraux, épilepsies, céphalées, sclérose en plaques et neuropathies.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 16,
    "totalQcms": 110,
    "totalCat": 7,
    "totalFiches": 13
  },
  {
    "id": "gastro",
    "slug": "gastro-enterologie",
    "name": "Gastro-entérologie & Hépatologie",
    "shortName": "Gastro-Hépato",
    "iconName": "Utensils",
    "color": "#10B981",
    "description": "Ulcères gastroduodénaux, cirrhose, hépatites virales, MICI, pancréatites et hémorragies digestives.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 16,
    "totalQcms": 105,
    "totalCat": 6,
    "totalFiches": 12
  },
  {
    "id": "infectieux",
    "slug": "infectiologie",
    "name": "Infectiologie & Maladies Transmissibles",
    "shortName": "Infectiologie",
    "iconName": "Bug",
    "color": "#14B8A6",
    "description": "Sepsis, antibiothérapie probabiliste, fièvres prolongées, méningites aiguës et zoonoses.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 17,
    "totalQcms": 115,
    "totalCat": 8,
    "totalFiches": 14
  },
  {
    "id": "hemato",
    "slug": "hematologie",
    "name": "Hématologie Clinique",
    "shortName": "Hématologie",
    "iconName": "Droplet",
    "color": "#BE123C",
    "description": "Anémies de l adulte et de l enfant, leucémies aiguës, lymphomes et troubles de l hémostase.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 13,
    "totalQcms": 85,
    "totalCat": 5,
    "totalFiches": 10
  },
  {
    "id": "endocrino",
    "slug": "endocrinologie",
    "name": "Endocrinologie - Diabétologie",
    "shortName": "Endocrinologie",
    "iconName": "Flame",
    "color": "#F59E0B",
    "description": "Diabète de type 1 et 2, dysthyroïdies, pathologies surrénaliennes et hypophysaires.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 14,
    "totalQcms": 90,
    "totalCat": 5,
    "totalFiches": 11
  },
  {
    "id": "nephro",
    "slug": "nephrologie",
    "name": "Néphrologie",
    "shortName": "Néphrologie",
    "iconName": "ActivitySquare",
    "color": "#3B82F6",
    "description": "Insuffisance rénale aiguë et chronique, néphropathies glomérulaires et troubles ioniques.",
    "year": 4,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 80,
    "totalCat": 5,
    "totalFiches": 9
  },
  {
    "id": "pediatrie",
    "slug": "pediatrie",
    "name": "Pédiatrie & Puériculture",
    "shortName": "Pédiatrie",
    "iconName": "Baby",
    "color": "#EC4899",
    "description": "Développement psychomoteur, déshydratation aiguë, bronchiolite, méningites de l enfant.",
    "year": 5,
    "faculty": "TOUS",
    "totalCourses": 20,
    "totalQcms": 130,
    "totalCat": 9,
    "totalFiches": 15
  },
  {
    "id": "gyneco",
    "slug": "gynecologie-obstetrique",
    "name": "Gynécologie - Obstétrique",
    "shortName": "Gynéco-Obs",
    "iconName": "HeartHandshake",
    "color": "#F43F5E",
    "description": "Grossesse extra-utérine, pré-éclampsie, hémorragie de la délivrance et cancers gynécologiques.",
    "year": 5,
    "faculty": "TOUS",
    "totalCourses": 15,
    "totalQcms": 95,
    "totalCat": 7,
    "totalFiches": 11
  },
  {
    "id": "psy",
    "slug": "psychiatrie",
    "name": "Psychiatrie & Pédopsychiatrie",
    "shortName": "Psychiatrie",
    "iconName": "Smile",
    "color": "#6366F1",
    "description": "Troubles de l humeur, schizophrénie, crises d angoisse aiguës, urgences suicidaires et addictions.",
    "year": 5,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 70,
    "totalCat": 5,
    "totalFiches": 8
  },
  {
    "id": "uro",
    "slug": "urologie",
    "name": "Urologie",
    "shortName": "Urologie",
    "iconName": "ShieldAlert",
    "color": "#059669",
    "description": "Colique néphrétique, torsion du cordon spermatique, rétention aiguë d urine et cancers urologiques.",
    "year": 5,
    "faculty": "TOUS",
    "totalCourses": 11,
    "totalQcms": 75,
    "totalCat": 5,
    "totalFiches": 8
  },
  {
    "id": "ortho",
    "slug": "orthopedie-traumatologie",
    "name": "Orthopédie & Traumatologie",
    "shortName": "Orthopédie",
    "iconName": "Footprints",
    "color": "#78716C",
    "description": "Fractures ouvertes, luxations articulaires, syndrome des loges, polytraumatisme et lésions sportives.",
    "year": 5,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 80,
    "totalCat": 6,
    "totalFiches": 9
  },
  {
    "id": "chirurgie",
    "slug": "chirurgie-generale",
    "name": "Chirurgie Générale & Viscérale",
    "shortName": "Chirurgie Viscérale",
    "iconName": "Scissors",
    "color": "#D97706",
    "description": "Appendicite aiguë, péritonite, occlusion intestinale, traumatismes abdominaux et hernies.",
    "year": 5,
    "faculty": "TOUS",
    "totalCourses": 14,
    "totalQcms": 90,
    "totalCat": 7,
    "totalFiches": 11
  },
  {
    "id": "rhumato",
    "slug": "rhumatologie",
    "name": "Rhumatologie",
    "shortName": "Rhumatologie",
    "iconName": "Bone",
    "color": "#84CC16",
    "description": "Polyarthrite rhumatoïde, spondyloarthrites, arthrites septiques, goutte et lombalgies.",
    "year": 5,
    "faculty": "TOUS",
    "totalCourses": 12,
    "totalQcms": 75,
    "totalCat": 4,
    "totalFiches": 9
  },
  {
    "id": "urgences",
    "slug": "urgences-reanimation",
    "name": "Urgences & Réanimation Médicale",
    "shortName": "Urgences-Réa",
    "iconName": "Siren",
    "color": "#DC2626",
    "description": "Arrêt cardiorespiratoire, états de choc, coma non traumatique, détresse respiratoire aiguë.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 18,
    "totalQcms": 140,
    "totalCat": 12,
    "totalFiches": 16
  },
  {
    "id": "therapeutique",
    "slug": "therapeutique-medicale",
    "name": "Thérapeutique Médicale & Urgences",
    "shortName": "Thérapeutique",
    "iconName": "Pill",
    "color": "#EA580C",
    "description": "Prescription raisonnée, antibiothérapie probabiliste, antalgiques, anticoagulants et interactions.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 14,
    "totalQcms": 95,
    "totalCat": 8,
    "totalFiches": 12
  },
  {
    "id": "med_legale",
    "slug": "medecine-legale-droit",
    "name": "Médecine Légale & Droit Médical",
    "shortName": "Méd Légale",
    "iconName": "Scale",
    "color": "#64748B",
    "description": "Certificats médicaux, secret médical, thanatologie, blessures et responsabilité médicale.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 10,
    "totalQcms": 70,
    "totalCat": 3,
    "totalFiches": 8
  },
  {
    "id": "med_travail",
    "slug": "medecine-du-travail",
    "name": "Médecine du Travail & Toxicologie",
    "shortName": "Méd Travail",
    "iconName": "Briefcase",
    "color": "#71717A",
    "description": "Maladies professionnelles, accidents du travail, intoxications au CO, plomb et solvants.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 10,
    "totalQcms": 65,
    "totalCat": 3,
    "totalFiches": 7
  },
  {
    "id": "dermato",
    "slug": "dermatologie",
    "name": "Dermatologie - Vénérologie",
    "shortName": "Dermatologie",
    "iconName": "Sparkles",
    "color": "#EAB308",
    "description": "Psoriasis, eczéma, toxidermies médicamenteuses graves, mélanome et infections cutanées.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 11,
    "totalQcms": 70,
    "totalCat": 4,
    "totalFiches": 8
  },
  {
    "id": "ophtalmo",
    "slug": "ophtalmologie",
    "name": "Ophtalmologie",
    "shortName": "Ophtalmologie",
    "iconName": "Eye",
    "color": "#0284C7",
    "description": "Glaucome aigu par fermeture de l angle, décollement de rétine, œil rouge et douloureux.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 9,
    "totalQcms": 60,
    "totalCat": 4,
    "totalFiches": 7
  },
  {
    "id": "orl",
    "slug": "orl",
    "name": "O.R.L. & Chirurgie Cervico-Faciale",
    "shortName": "ORL",
    "iconName": "Headphones",
    "color": "#A855F7",
    "description": "Épistaxis grave, dyspnée laryngée, sinusites compliquées, vertiges périphériques et corps étrangers.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 10,
    "totalQcms": 65,
    "totalCat": 5,
    "totalFiches": 7
  },
  {
    "id": "interne",
    "slug": "medecine-interne",
    "name": "Médecine Interne",
    "shortName": "Méd Interne",
    "iconName": "Compass",
    "color": "#475569",
    "description": "Lupus érythémateux systémique, maladie de Horton, vascularites systémiques et amylose.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 10,
    "totalQcms": 70,
    "totalCat": 4,
    "totalFiches": 8
  },
  {
    "id": "epidemiologie",
    "slug": "epidemiologie-clinique",
    "name": "Épidémiologie & Médecine Préventive",
    "shortName": "Épidémiologie",
    "iconName": "BarChart2",
    "color": "#0284C7",
    "description": "Études épidémiologiques, enquêtes de prévalence, incidence, facteurs de risque et dépistage.",
    "year": 6,
    "faculty": "TOUS",
    "totalCourses": 8,
    "totalQcms": 55,
    "totalCat": 2,
    "totalFiches": 6
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_demo_free',
    email: 'demo@asmedix.com',
    name: 'Dr. Amine Zerrouki',
    username: 'amine_med',
    profession: 'Interne',
    specialty: 'Cardiologie',
    role: 'USER',
    plan: 'FREE',
    status: 'active',
    createdAt: '2026-08-15T10:00:00Z',
    lastActive: '2026-09-05T07:00:00Z',
    usage: {
      coursesViewedMonth: 1,
      qcmsAnsweredMonth: 14,
      fichesViewedMonth: 2,
      catViewedMonth: 1,
      casesViewedMonth: 1,
      resetDate: '2026-09-30T23:59:59Z'
    }
  },
  {
    id: 'usr_admin_master',
    email: 'admin@asmedix.com',
    name: 'Pr. Karim Benali',
    username: 'admin_asmedix',
    profession: 'Médecin',
    specialty: 'Pneumologie',
    role: 'ADMIN',
    plan: 'PREMIUM',
    status: 'active',
    createdAt: '2026-01-01T08:00:00Z',
    lastActive: '2026-09-05T07:15:00Z',
    usage: {
      coursesViewedMonth: 24,
      qcmsAnsweredMonth: 156,
      fichesViewedMonth: 42,
      catViewedMonth: 18,
      casesViewedMonth: 9,
      resetDate: '2026-09-30T23:59:59Z'
    }
  }
];

export const INITIAL_SETTINGS: PlatformSettings = {
  platformName: 'AS MEDIX',
  whatsappNumber: '+213 555 12 34 56',
  secondaryPhone: '+213 770 12 34 56',
  instagramUrl: 'https://instagram.com/asmedix_officiel',
  facebookUrl: 'https://facebook.com/asmedix_officiel',
  telegramUrl: 'https://t.me/asmedix_officiel',
  baridimobRip: '00799999002233445566',
  ccpNumber: '22334455 Clé 66',
  accountHolder: 'Dr. Karim Benali',
  supportEmail: 'contact@asmedix.dz',
  freeLimits: {
    maxCourses: 2,
    maxFiches: 3,
    maxQcmPerMonth: 20,
    maxCat: 2,
    maxCases: 1,
    maxEcg: 2
  },
  pricing: {
    freePriceDa: 0,
    proPriceDa: 4500,
    premiumPriceDa: 7000
  },
  aiConfig: {
    provider: 'mock',
    modelName: 'AS-Medix Med-Core 4.0',
    enabled: true
  },
  maintenanceMode: false,
  registrationsOpen: true
};
