-- SQL Query to update and sync 'courses' table columns in Supabase PostgreSQL
ALTER TABLE courses ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS author TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS author_title TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS cover_image TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS faculty TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS tags JSONB;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS access_level TEXT DEFAULT 'FREE';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT true;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS views_count INT DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS likes_count INT DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS qcm_count INT DEFAULT 5;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS table_of_contents JSONB;
